version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - <ecr login command>
      - <set image uri variable>
  build:
    commands:
      - echo Build started on `date`
      - <docker build command>
      - <docker tag command if needed>
  post_build:
    commands:
      - echo Pushing the Docker image...
      - <docker push command>
      - <write image artifact file if the lesson asks for one>

artifacts:
  files:
    - <artifact filename if required>
